name: mimi
favicon: null
layout_spectrum: 0.74174
typography_spectrum: 0.10556
title: mimi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#35353d'
    - '#9f8b94'
    - '#ccd8ce'
    - '#ff95a9'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
