title: mimi
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5463079
  brandStrength: 0.9072682
  rhythmicContrast: 0.5375469
  brandColors:
    - '#CBFCFF'
    - '#28022B'
    - '#85446E'
    - '#74D8FA'
    - '#2EADDA'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  facebook: null
  google: null
favicon: null
name: mimi
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0669587
layout_spectrum: 0.8339599
