name: mimi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10556
title: mimi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000403'
    - '#f6f2f3'
    - '#75b1ef'
    - '#0078ce'
    - '#856fb0'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
