title: mimi
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8804756
favicon: null
name: mimi
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0
  lightness: 1
  saturation: 0.5463079
  rhythmicContrast: 0.5375469
  brandColors:
    - '#000403'
    - '#f6f2f3'
    - '#75b1ef'
    - '#0078ce'
    - '#856fb0'
typography_spectrum: 0.0669587
