title: mimi
cta:
  domain: null
  bucket: null
  version: null
layout_spectrum: 0.8339599
favicon: null
name: mimi
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8479349
  lightness: 1
  saturation: 0.5463079
  rhythmicContrast: 0.5375469
  brandColors:
    - '#CBFCFF'
    - '#28022B'
    - '#85446E'
    - '#74D8FA'
    - '#2EADDA'
typography_spectrum: 0.0669587
